# Generated by Django 4.2.16 on 2025-02-16 23:27

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('avatar', models.ImageField(blank=True, default='default_avatars/default_avatar.png', null=True, upload_to='avatars/')),
                ('bank_name', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_code', models.IntegerField(blank=True, null=True)),
                ('bank_currency', models.CharField(blank=True, default='NGN', max_length=20, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=10, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=30, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(editable=False, max_length=255, unique=True)),
                ('asset_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('hotel', 'Hotel')], max_length=10)),
                ('asset_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('details', models.JSONField()),
                ('account_number', models.CharField(max_length=10)),
                ('bank', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('access', 'Access'), ('location', 'Location'), ('occupancy', 'Occupancy'), ('electricity', 'Electricity'), ('ignition', 'Ignition'), ('passenger_count', 'Passenger Count')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.CharField(max_length=255)),
                ('object_id', models.CharField(max_length=10)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.asset', to_field='asset_number')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_latitude', models.FloatField(default=0, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('total_distance', models.FloatField(default=0.0)),
                ('vehicle_number', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('activation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('expiry_timestamp', models.DateTimeField(blank=True, null=True)),
                ('fleet', models.ForeignKey(limit_choices_to={'asset_type': 'vehicle'}, on_delete=django.db.models.deletion.CASCADE, related_name='fleet', to='core.asset', to_field='asset_number')),
            ],
            options={
                'unique_together': {('fleet', 'vehicle_number')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('sub_asset_number', models.CharField(max_length=10, null=True)),
                ('transaction_ref', models.CharField(max_length=255, unique=True)),
                ('processor_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('reversed', 'Reversed')], max_length=10)),
                ('payment_type', models.CharField(choices=[('card', 'Card'), ('transfer', 'Transfer'), ('mobile_money', 'Mobile_money')], max_length=100)),
                ('is_outgoing', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.asset', to_field='asset_number')),
            ],
            options={
                'indexes': [models.Index(fields=['transaction_ref'], name='core_transa_transac_22fca0_idx'), models.Index(fields=['payment_status'], name='core_transa_payment_67d780_idx'), models.Index(fields=['timestamp'], name='core_transa_timesta_a5c12f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('viewer', 'Viewer')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.asset', to_field='asset_number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='PaystackTransferRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_code', models.CharField(max_length=63, unique=True)),
                ('bank_account_number', models.CharField(max_length=15)),
                ('bank_code', models.CharField(max_length=15)),
                ('bank_name', models.CharField(max_length=32)),
                ('bank_account_name', models.CharField(max_length=127)),
                ('currency', models.CharField(default='NGN', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_transfer_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer Recipient',
                'verbose_name_plural': 'Transfer Recipients',
                'unique_together': {('bank_account_number', 'bank_code')},
            },
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('room_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=False)),
                ('activation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('expiry_timestamp', models.DateTimeField(blank=True, null=True)),
                ('hotel', models.ForeignKey(limit_choices_to={'asset_type': 'hotel'}, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.asset', to_field='asset_number')),
            ],
            options={
                'unique_together': {('hotel', 'room_number')},
            },
        ),
    ]
